import React, { createContext, useContext, useMemo, useState, ReactNode } from "react";

export type Language = "zh-TW" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  "zh-TW": {
    // nav
    elderPortal: "長輩介面",
    familyPortal: "家屬介面",
    admin: "管理員",
    // hero
    heroTag: "桃竹苗地區長照社會創新 NPO",
    heroTitle: "用捐血換取居家照護，守護長輩、留住回憶",
    heroDesc: "Vigil Keepers 提供整合健康監測、媒體播放與數位遺產的一體式居家照護設備。每次捐血累積點數，可直接折抵設備費用，讓善心捐血成為守護家人最實際的方式。",
    elderEntry: "長輩入口",
    familyDashboard: "家屬管理介面",
    // stats
    statsAreaValue: "桃竹苗",
    statsAreaLabel: "服務區域",
    statsDeviceValue: "1 台",
    statsDeviceLabel: "整合式照護設備",
    statsPrivacyValue: "100%",
    statsPrivacyLabel: "家屬同意才開放查看",
    statsDiscountValue: "0 元",
    statsDiscountLabel: "捐血達標即享折扣",
    // services
    servicesTitle: "我們提供什麼",
    servicesSubtitle: "三項核心服務，讓長照更有溫度、更有保障。",
    s1Title: "居家安全監測",
    s1Desc: "整合健康監測、行動偵測與緊急警報，讓家屬即時掌握長輩的居家狀況，有事立即通知。",
    s2Title: "捐血點數兌換",
    s2Desc: "每次捐血可累積點數，用於折抵照護設備租賃費用。善心捐血直接轉化為自身或家人的長照保障。",
    s3Title: "數位遺產保存",
    s3Desc: "設備自動播放家屬上傳的影片與照片，減少長輩被遺忘感。家屬也可委託後製，留存珍貴回憶。",
    // steps
    stepsTitle: "服務流程",
    stepsSubtitle: "從捐血到守護長輩，四個簡單步驟。",
    step1Title: "前往捐血",
    step1Desc: "至新竹捐血中心（桃竹苗地區）完成捐血。",
    step2Title: "累積點數",
    step2Desc: "捐血次數由我方轉換為照護點數。",
    step3Title: "申請設備",
    step3Desc: "以點數折抵設備租賃或買斷費用。",
    step4Title: "居家守護",
    step4Desc: "設備安裝到位，長輩安全即時回報家屬。",
    // partners
    partnersTitle: "關鍵合作夥伴",
    partnersSubtitle: "與專業機構協力，共同實現長照社會創新。",
    p1Name: "新竹捐血中心",
    p1Note: "台灣血液基金會 · 桃竹苗地區",
    p2Name: "國立中央大學",
    p2Note: "機械／電機／資工系 · 設備研發",
    p3Name: "法律與公證顧問",
    p3Note: "契約保障 · 資料合規",
    p4Name: "Google／Amazon",
    p4Note: "雲端算力與安全儲存支援",
    // commitments
    commitTitle: "我們對您的承諾",
    commitDesc: "這項服務涉及長輩的隱私與家屬的安心，我們以透明與尊重為首要原則。",
    c1: "價格透明，無隱藏費用",
    c2: "高隱私性，家屬同意才開放查看",
    c3: "設備操作簡易，適合長輩使用",
    c4: "家屬可自行上傳內容，增進互動",
    // footer
    footerDesc: "桃竹苗長照社會創新 NPO，結合捐血點數、居家照護設備與數位遺產服務，讓善行成為家人最好的長照保障。",
    footerCopy: "© 2026 Vigil Keepers · 守護者計畫 · 非營利組織",
    address: "桃園市中壢區中大路 300 號",
    // pages
    home: "首頁",
    health: "健康",
    message: "訊息",
    healthReports: "健康報告",
    deviceManagement: "設備管理",
    mediaUpload: "回憶上傳",
    welcomeBack: "歡迎回來",
    watchVideo: "觀看導覽",
    todayFeeling: "今天感覺如何？",
    checkHealth: "查看今日健康狀況",
    newMessages: "閱讀家人動態",
    dashboard: "家屬儀表板",
    dailyHealthStatus: "每日健康狀況",
    pointBalance: "照護點數餘額",
    heartRate: "心率",
    bloodPressure: "血壓",
    steps: "步數",
    uploadPhoto: "上傳照片",
    uploadVideo: "上傳影片",
    recentMedia: "近期回憶",
    socialInnovation: "長輩照護服務",
    elderlyCare: "為長輩與家屬提供實際的照護支援",
    businessModel: "讓日常照護更輕鬆的協調服務",
    step1: "每日健康回報",
    step1Old: "簡單的日常流程幫助長輩回報狀況，讓家屬隨時掌握。",
    step2: "家屬協調",
    step2Old: "照護更新、提醒與訊息讓所有人保持同步。",
    step3: "照護服務支援",
    step3Old: "連結家屬與實際照護服務及補助申請流程。",
    learnMore: "探索服務",
    viewDetails: "查看詳情",
    upload: "上傳",
    manage: "管理",
    // shared ui
    back: "返回",
    logout: "登出",
    send: "傳送",
    // admin dashboard
    adminConsoleTitle: "管理員主控台",
    adminConsoleDesc: "服務運作、照護需求與團隊協調",
    adminModeBadge: "管理員模式",
    adminHeroTitle: "用明確的優先順序協調照護服務。",
    adminHeroDesc: "管理員可從一個主控台監控服務需求、查看異常情況、分配照護人員並保持家屬知情。",
    reviewSchedule: "查看排程",
    activeElders: "服務中長輩",
    activeEldersDetail: "今日 6 位需追蹤",
    careWorkers: "照護人員",
    careWorkersDetail: "18 位目前已指派",
    openRequests: "待處理需求",
    openRequestsDetail: "4 件高優先",
    careRequestQueue: "照護需求待辦",
    todayScheduleTitle: "今日照護排程",
    priorityHigh: "高",
    priorityMedium: "中",
    priorityLow: "低",
    queueIssue1: "未服藥",
    queueElder1: "陳女士",
    queueAction1: "指派護理師回電",
    queueIssue2: "家屬要求更改探訪",
    queueElder2: "林先生",
    queueAction2: "確認新排程",
    queueIssue3: "設備同步延遲",
    queueElder3: "黃先生",
    queueAction3: "傳送設定指南",
    scheduleTask1: "居家探訪",
    scheduleLoc1: "大安區",
    scheduleStatus1: "已指派",
    scheduleTask2: "健康評估",
    scheduleLoc2: "遠端",
    scheduleStatus2: "待補記錄",
    scheduleTask3: "照護計畫更新",
    scheduleLoc3: "中山區",
    scheduleStatus3: "已確認",
    // family dashboard
    familyDashboardTitle: "家屬儀表板",
    familyDashboardDesc: "家屬共同照護的可視化介面",
    familyModeBadge: "家屬模式",
    familyHeroTitle: "讓所有家屬圍繞日常照護保持同步。",
    familyHeroDesc: "家屬可以查看健康更新、協調任務、傳訊給長輩，並了解照護團隊已處理的事項。",
    messageElder: "傳訊給長輩",
    callCareTeam: "聯絡照護團隊",
    priorityNotice: "重要通知",
    medicationRefillNeeded: "需要補充藥品",
    medicationRefillDesc: "目前的處方藥物預計本週五用完，請指派一位家屬確認補領。",
    assignTask: "指派任務",
    fCareStatus: "照護狀態",
    fCareStatusValue: "穩定",
    fCareStatusDetail: "今早 8:45 完成健康確認",
    fHeartRate: "心率",
    fHeartRateValue: "72 次/分",
    fHeartRateDetail: "在正常範圍內",
    fNextVisit: "下次探訪",
    fNextVisitValue: "明天",
    fNextVisitDetail: "照護人員 10:00 到訪",
    todayCareTimeline: "今日照護時間軸",
    sharedResponsibilities: "共同責任分工",
    update1Title: "健康確認完成",
    update1Detail: "心情與食慾回報正常。",
    update2Title: "用藥提醒",
    update2Detail: "午餐用藥提醒已設定。",
    update3Title: "家人留言",
    update3Detail: "女兒確認週末探訪。",
    resp1Task: "補充處方藥",
    resp1Due: "本週五前",
    resp1Owner: "由 Mei 負責",
    resp2Task: "醫師預約",
    resp2Due: "5月28日 10:30",
    resp2Owner: "由 David 負責",
    resp3Task: "採買協助",
    resp3Due: "每週",
    resp3Owner: "由 Anna 負責",
    // health page
    wellnessStatusStable: "健康狀態穩定",
    todayWellness: "今日健康",
    todayWellnessDesc: "簡單呈現重要的健康指標、服藥時間與即將到來的照護支援。",
    hHeartRate: "心率",
    hHeartRateValue: "72 次/分",
    hHeartRateDetail: "正常",
    hBloodPressure: "血壓",
    hBloodPressureValue: "120/80",
    hBloodPressureDetail: "最佳",
    hMedication: "用藥",
    hMedicationValue: "今日 1 次",
    hMedicationDetail: "午餐提醒",
    hCareVisit: "照護探訪",
    hCareVisitValue: "明天",
    hCareVisitDetail: "上午 10:00",
    // messages page
    callFamily: "撥打給家人",
    familyConnection: "家庭連結",
    messagesTitle: "訊息與照護更新",
    messagesDesc: "讓家屬與照護協助者透過清晰的更新，在同一個地方保持同步。",
    messagePlaceholder: "給家人留言",
    msgSender1: "家人",
    msgText1: "媽媽今早確認後說感覺很好。",
    msgSender2: "照護團隊",
    msgText2: "午餐用藥提醒已設定。",
    msgSender3: "女兒",
    msgText3: "我今天下班後會去探訪。",
    // login page
    backToWorkspace: "返回入口選擇",
    adminLoginTitle: "管理員登入",
    adminEyebrow: "管理員模式",
    adminLoginDesc: "適合管理長輩、照護團隊、排程與需求的服務運營者。",
    adminButton: "進入管理主控台",
    elderLoginTitle: "長輩使用者登入",
    elderEyebrow: "長輩模式",
    elderLoginDesc: "適合使用健康確認、提醒、訊息與家庭聯絡的長輩。",
    elderButton: "進入長輩介面",
    familyLoginTitle: "家屬登入",
    familyEyebrow: "家屬模式",
    familyLoginDesc: "適合查看更新、任務、探訪與照護溝通的家屬。",
    familyButton: "進入家屬儀表板",
    userId: "使用者帳號",
    password: "密碼",
    passwordPlaceholder: "示範密碼",
    prototypeNote: "原型說明：每次登入只會在此瀏覽器工作階段啟用所選模式。",
    switchModeWarning: "您目前已登入其他模式，繼續將會把此工作階段切換為",
    // elder home
    personalCareCompanion: "個人照護夥伴",
    checkWellnessBtn: "查看健康",
    contactFamily: "聯絡家人",
    elderCareStatus: "照護狀態",
    elderCareStatusValue: "一切正常",
    elderCareStatusDetail: "最後確認 8:45 AM",
    elderMedication: "用藥",
    elderMedicationValue: "下次：12:30",
    elderMedicationDetail: "午餐提醒已備妥",
    elderVisit: "照護探訪",
    elderVisitValue: "明天",
    elderVisitDetail: "照護人員 10:00 到訪",
  },
  en: {
    // nav
    elderPortal: "Elder View",
    familyPortal: "Family View",
    admin: "Admin",
    // hero
    heroTag: "NPO for Elder Care Innovation · Taoyuan Region",
    heroTitle: "Blood Donation Points for Elder Care — Monitor, Connect, and Preserve Memories",
    heroDesc: "Vigil Keepers provides an all-in-one home care device combining health monitoring, family media playback, and digital legacy recording. Donate blood to earn points redeemable for device discounts — turning every donation into lasting care for your loved ones.",
    elderEntry: "Elder Portal",
    familyDashboard: "Family Dashboard",
    // stats
    statsAreaValue: "Taoyuan",
    statsAreaLabel: "Service Region",
    statsDeviceValue: "1 Unit",
    statsDeviceLabel: "Integrated Care Device",
    statsPrivacyValue: "100%",
    statsPrivacyLabel: "Consent required to view",
    statsDiscountValue: "Free",
    statsDiscountLabel: "Device discount via blood donation",
    // services
    servicesTitle: "What We Offer",
    servicesSubtitle: "Three core services to make elder care warmer and more secure.",
    s1Title: "Home Safety Monitoring",
    s1Desc: "Integrated health monitoring, motion detection and emergency alerts so family members can track elders' safety at home in real time.",
    s2Title: "Blood Donation Points",
    s2Desc: "Earn points with every blood donation and redeem them against device rental fees — turning altruism directly into long-term care support.",
    s3Title: "Digital Legacy",
    s3Desc: "The device auto-plays photos and videos uploaded by family, reducing elders' sense of isolation. Custom editing also available.",
    // steps
    stepsTitle: "How It Works",
    stepsSubtitle: "Four simple steps from blood donation to elder care.",
    step1Title: "Donate Blood",
    step1Desc: "Visit the Hsinchu Blood Donation Center serving the Taoyuan region.",
    step2Title: "Earn Points",
    step2Desc: "We convert your donation count into care points.",
    step3Title: "Apply for Device",
    step3Desc: "Use points to offset device rental or purchase costs.",
    step4Title: "Home Protection",
    step4Desc: "Device installed — elder safety reported to family in real time.",
    // partners
    partnersTitle: "Key Partners",
    partnersSubtitle: "Collaborating with trusted institutions to drive elder care innovation.",
    p1Name: "Hsinchu Blood Center",
    p1Note: "Taiwan Blood Services Foundation · Taoyuan Region",
    p2Name: "National Central University",
    p2Note: "ME / EE / CS Departments · Device R&D",
    p3Name: "Legal & Notary Advisors",
    p3Note: "Contract protection · Data compliance",
    p4Name: "Google / Amazon",
    p4Note: "Cloud computing and secure storage",
    // commitments
    commitTitle: "Our Commitments to You",
    commitDesc: "This service handles elders' privacy and family peace of mind — transparency and respect are our foundation.",
    c1: "Transparent pricing, no hidden fees",
    c2: "High privacy: family consent required to view content",
    c3: "Easy-to-use device suitable for elderly users",
    c4: "Family can upload content anytime to enhance interaction",
    // footer
    footerDesc: "NPO for elder care innovation in the Taoyuan region, combining blood donation points, home care devices, and digital legacy services.",
    footerCopy: "© 2026 Vigil Keepers · Guardian Program · Non-Profit Organization",
    address: "No. 300, Zhongda Rd., Zhongli District, Taoyuan City",
    // pages
    home: "Home",
    health: "Health",
    message: "Message",
    healthReports: "Health Reports",
    deviceManagement: "Device Management",
    mediaUpload: "Memory Upload",
    welcomeBack: "Welcome back",
    watchVideo: "Watch guide",
    todayFeeling: "How are you feeling today?",
    checkHealth: "Check today's wellness status",
    newMessages: "Read family updates",
    dashboard: "Family dashboard",
    dailyHealthStatus: "Daily health status",
    pointBalance: "Care credit balance",
    heartRate: "Heart rate",
    bloodPressure: "Blood pressure",
    steps: "Steps",
    uploadPhoto: "Upload photo",
    uploadVideo: "Upload video",
    recentMedia: "Recent memories",
    socialInnovation: "Elder support services",
    elderlyCare: "Practical care support for elders and families",
    businessModel: "Coordinated services that make daily care easier",
    step1: "Daily wellness check-ins",
    step1Old: "Simple routines help elders report how they feel and stay visible to family.",
    step2: "Family coordination",
    step2Old: "Care updates, reminders, and messages keep everyone aligned.",
    step3: "Care service support",
    step3Old: "Connect families with practical care services and subsidy workflows.",
    learnMore: "Explore services",
    viewDetails: "View details",
    upload: "Upload",
    manage: "Manage",
    // shared ui
    back: "Back",
    logout: "Logout",
    send: "Send",
    // admin dashboard
    adminConsoleTitle: "Administrator console",
    adminConsoleDesc: "Service operations, care requests, and team coordination",
    adminModeBadge: "Admin mode",
    adminHeroTitle: "Coordinate care services with clear priorities.",
    adminHeroDesc: "Administrators can monitor service demand, review exceptions, assign care workers, and keep families informed from one console.",
    reviewSchedule: "Review schedule",
    activeElders: "Active elders",
    activeEldersDetail: "6 require follow-up today",
    careWorkers: "Care workers",
    careWorkersDetail: "18 currently assigned",
    openRequests: "Open requests",
    openRequestsDetail: "4 high priority",
    careRequestQueue: "Care request queue",
    todayScheduleTitle: "Today's care schedule",
    priorityHigh: "High",
    priorityMedium: "Medium",
    priorityLow: "Low",
    queueIssue1: "Medication missed",
    queueElder1: "Mrs. Chen",
    queueAction1: "Assign nurse callback",
    queueIssue2: "Family requested visit change",
    queueElder2: "Mr. Lin",
    queueAction2: "Confirm new schedule",
    queueIssue3: "Device sync delayed",
    queueElder3: "Mr. Huang",
    queueAction3: "Send setup guide",
    scheduleTask1: "Home visit",
    scheduleLoc1: "Da'an District",
    scheduleStatus1: "Assigned",
    scheduleTask2: "Wellness review",
    scheduleLoc2: "Remote",
    scheduleStatus2: "Pending notes",
    scheduleTask3: "Care plan update",
    scheduleLoc3: "Zhongshan District",
    scheduleStatus3: "Confirmed",
    // family dashboard
    familyDashboardTitle: "Family dashboard",
    familyDashboardDesc: "Shared care visibility for family members",
    familyModeBadge: "Family mode",
    familyHeroTitle: "Keep everyone aligned around daily care.",
    familyHeroDesc: "Family members can review health updates, coordinate tasks, message the elder, and see what the care team has already handled.",
    messageElder: "Message elder",
    callCareTeam: "Call care team",
    priorityNotice: "Priority notice",
    medicationRefillNeeded: "Medication refill needed",
    medicationRefillDesc: "The current prescription supply is estimated to run low this Friday. Assign one family member to confirm refill pickup.",
    assignTask: "Assign task",
    fCareStatus: "Care status",
    fCareStatusValue: "Stable",
    fCareStatusDetail: "Last wellness check at 8:45 AM",
    fHeartRate: "Heart rate",
    fHeartRateValue: "72 bpm",
    fHeartRateDetail: "Within usual range",
    fNextVisit: "Next visit",
    fNextVisitValue: "Tomorrow",
    fNextVisitDetail: "Care assistant at 10:00 AM",
    todayCareTimeline: "Today's care timeline",
    sharedResponsibilities: "Shared responsibilities",
    update1Title: "Wellness check completed",
    update1Detail: "Mood and appetite reported normal.",
    update2Title: "Medication reminder",
    update2Detail: "Lunch medication reminder is scheduled.",
    update3Title: "Family note",
    update3Detail: "Daughter confirmed weekend visit.",
    resp1Task: "Medication refill",
    resp1Due: "Due Friday",
    resp1Owner: "Assigned to Mei",
    resp2Task: "Doctor appointment",
    resp2Due: "May 28, 10:30 AM",
    resp2Owner: "Assigned to David",
    resp3Task: "Grocery support",
    resp3Due: "Weekly",
    resp3Owner: "Assigned to Anna",
    // health page
    wellnessStatusStable: "Wellness status stable",
    todayWellness: "Today's wellness",
    todayWellnessDesc: "A simple view of important health signals, medication timing, and upcoming care support.",
    hHeartRate: "Heart rate",
    hHeartRateValue: "72 bpm",
    hHeartRateDetail: "Normal",
    hBloodPressure: "Blood pressure",
    hBloodPressureValue: "120/80",
    hBloodPressureDetail: "Optimal",
    hMedication: "Medication",
    hMedicationValue: "1 due today",
    hMedicationDetail: "Lunch reminder",
    hCareVisit: "Care visit",
    hCareVisitValue: "Tomorrow",
    hCareVisitDetail: "10:00 AM",
    // messages page
    callFamily: "Call family",
    familyConnection: "Family connection",
    messagesTitle: "Messages and care updates",
    messagesDesc: "Keep family members and care helpers aligned with clear updates in one place.",
    messagePlaceholder: "Write a message to family",
    msgSender1: "Family",
    msgText1: "Mom checked in this morning and said she felt well.",
    msgSender2: "Care team",
    msgText2: "Medication reminder is scheduled for lunch.",
    msgSender3: "Daughter",
    msgText3: "I will visit after work today.",
    // login page
    backToWorkspace: "Back to workspace selection",
    adminLoginTitle: "Administrator login",
    adminEyebrow: "Admin mode",
    adminLoginDesc: "For service operators managing elders, care teams, schedules, and requests.",
    adminButton: "Enter admin console",
    elderLoginTitle: "Elder user login",
    elderEyebrow: "Elder mode",
    elderLoginDesc: "For elders using wellness check-ins, reminders, messages, and family contact.",
    elderButton: "Enter elder view",
    familyLoginTitle: "Family login",
    familyEyebrow: "Family mode",
    familyLoginDesc: "For family members reviewing updates, tasks, visits, and care communication.",
    familyButton: "Enter family dashboard",
    userId: "User ID",
    password: "Password",
    passwordPlaceholder: "Prototype password",
    prototypeNote: "Prototype note: each login activates only this selected mode in the browser session.",
    switchModeWarning: "You are currently signed into another mode. Continuing here will switch this browser session to",
    // elder home
    personalCareCompanion: "Personal care companion",
    checkWellnessBtn: "Check wellness",
    contactFamily: "Contact family",
    elderCareStatus: "Care status",
    elderCareStatusValue: "All good",
    elderCareStatusDetail: "Last check-in 8:45 AM",
    elderMedication: "Medication",
    elderMedicationValue: "Next: 12:30",
    elderMedicationDetail: "Lunch reminder ready",
    elderVisit: "Visit",
    elderVisitValue: "Tomorrow",
    elderVisitDetail: "Care assistant at 10:00",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("zh-TW");

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] || key,
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
